[package]
name = "demo_crm_embedded"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "demo_crm_embedded"

[dependencies]
thiserror = "2.0.20"
serde_json = "1.0.151"
dino-sdk = { version = "=0.2.0-rc.1", features = ["guest"] }

[workspace]

[workspace.lints.clippy]
cast_possible_truncation = "forbid"
cast_possible_wrap = "forbid"
cast_sign_loss = "forbid"
cast_precision_loss = "forbid"

[lints]
workspace = true
